# Generated by Django 6.0.3 on 2026-03-21 15:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ngo_id', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('security_code', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified by Admin')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('RESTAURANT', 'Restaurant Donor'), ('INDIVIDUAL_DONOR', 'Individual Donor'), ('NGO_VOLUNTEER', 'NGO Volunteer'), ('INDIVIDUAL_VOLUNTEER', 'Individual Volunteer')], max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('fssai_license', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('ngo_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified_ngo', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('food_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(help_text='Servings')),
                ('image', models.ImageField(upload_to='food_images/')),
                ('preservation_required', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Claimed', 'Claimed'), ('Verified', 'Verified')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
