# Generated by Django 6.0.1 on 2026-02-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified by Admin'),
        ),
    ]
